export default [
	{
		name: "landmine",
		faction: "autobot",
		health: 10,
		firepower: 5,
		speed: 3,
		range: 5,
    image: "landmine.png",
	},
	{
		name: "ransack",
		faction: "ransack",
		health: 5,
		firepower: 3,
		speed: 5,
		range: 5,
    image: "ransack.png",
	},
	{
		name: "dunerunner",
		faction: "autobot",
		health: 5,
		firepower: 3,
		speed: 5,
		range: 7,
		image: "dunerunner.png",
	},
	{
		name: "prowl",
		faction: "ransack",
		health: 10,
		firepower: 2,
		speed: 3,
		range: 6,
		image: "prowl.png",
	},
	{
		name: "brainstorm",
		faction: "autobot",
		health: 10,
		firepower: 2,
		speed: 6,
		range: 8,
    image: "brainstorm.png",
	},
	{
    name: "overcast",
		faction: "ransack",
		health: 10,
		firepower: 2,
		speed: 6,
		range: 8,
    image: "overcast.png",
	},
	{
		name: "ironhide",
		faction: "autobot",
		health: 20,
		firepower: 3,
		speed: 3,
		range: 4,
    image: "ironhide.png",
	},
	{
		name: "onslaught",
		faction: "ransack",
		health: 30,
		firepower: 4,
		speed: 2,
		range: 4,
		image: "onslaught.png",
	},
	{
		name: "overhaul",
		faction: "autobot",
		health: 10,
		firepower: 3,
		speed: 5,
		range: 0,
		image: "overhaul.png",
	},
	{
		name: "crumplezone",
		faction: "ransack",
		health: 20,
		firepower: 2,
		speed: 5,
		range: 5,
    image: "crumplezone.png",
	},
]